### ISSUE TITLE
🚧Impletement Associative Container Skip List

### ISSUE THREAD

**Issue by LebranceBW** [weihanglo/rust-algorithm-club#45]
I want to accomplish the "Skip list" for searching. Used in [leveldb](https://github.com/google/leveldb). However, I could only make it with unsafe Rust and not sure there are no memory leak.
- [x] Skip list.

**Comment by weihanglo** [comment]
Sounds great! Unsafe code is acceptable if you cannot avoid it. Just make sure the code is intuitive and clear as a learning resource.

FYI, Redis also uses [skip list](https://github.com/redis/redis/blob/62b1f32/src/t_zset.c#L79-L95) as an internal data structure.

**Comment by LebranceBW** [comment]
🚀 yeah, I will set out after Spring Festival.
